# Generated by Django 3.1.5 on 2021-01-14 20:13

from django.db import migrations, models
import sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sliders.models.upload_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(max_length=100, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
