# Generated by Django 3.1.5 on 2021-01-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copy_right',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
