# Generated by Django 3.1.5 on 2021-01-20 04:06

from django.db import migrations, models
import site_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=site_settings.models.upload_image_path, verbose_name='تصویر لوگو'),
        ),
    ]
