# Generated by Django 3.1.5 on 2021-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_auto_20210113_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
