# Generated by Django 3.1.5 on 2021-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210114_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
